-- Harden CEO Control API keys: store a SHA-256 hash instead of the raw secret,
-- and add a non-secret masked preview for the dashboard.
--
-- NOTE: existing rows hold raw keys. Because hashing is one-way, previously
-- issued keys cannot be back-filled into hashes and must be re-generated by
-- their owners. Any raw keys are revoked here so they can no longer be used
-- (a raw key would never match a SHA-256 lookup anyway).

ALTER TABLE public.ceo_api_keys
  ADD COLUMN IF NOT EXISTS key_preview varchar(64);

-- Revoke legacy raw keys: they predate hashing and will not validate.
UPDATE public.ceo_api_keys
  SET status = 'revoked',
      updated_at = now()
  WHERE status = 'active'
    AND api_key NOT SIMILAR TO '[0-9a-f]{64}';
